### ISSUE TITLE
Viscosity for electrolytes

### ISSUE THREAD

**Issue by matteo-northvolt** [drcassar/viscnet#2]
Good morning,

I was wondering if you have tested viscnet on electrolytes or on solvents used in the battery field (e.g., carbonate-based solvents).

Thanks,

  Matteo

**Comment by drcassar** [comment]
Hi Matteo,
I'm afraid that ViscNet was not trained with the compositions you are interested. You can check all the data used for training in the data file https://github.com/drcassar/viscnet/blob/main/viscnet/files/data.csv.xz.
Thanks,
Daniel
